name: printenv

on:
  push:

jobs:
  curl:
    name: "printenv"
    runs-on: "ghcr.io/cirruslabs/macos-runner:sequoia"
    steps:
      - name: printenv
        run: printenv
      - name: cURL
        run: echo curl -I http://${{ env.CIRRUS_HTTP_CACHE_HOST }}
